import { Icon } from '@components';
import { BaseLayout } from '@layouts';
import { useTranslation } from 'next-i18next';
import Head from 'next/head';
import React from 'react';
import { NextPageWithProps } from 'types/customTypes';

interface HomePageProps {
  
}

const Home: NextPageWithProps = (props: HomePageProps) => {
  const { t } = useTranslation('common');
  return (
    <>
      <Head>
        <title>NextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
     <h1> {t("hello")}</h1>
     <Icon type='clock'/>
    </>
  );
};

Home.mainLayout = BaseLayout;
// Home.childLayout = SubLayout;
export default Home;
