import { Splash } from '@components';
import { BaseLayout } from '@layouts';
import { useTranslation } from 'next-i18next';
import Head from 'next/head';
import React from 'react';
import { NextPageWithProps } from 'types/customTypes';

interface SplashPagePageProps {
  
}

const SplashPage: NextPageWithProps = (props: SplashPagePageProps) => {
  const { t } = useTranslation('common');
  return (
    <>
      <Head>
        <title>NextJs</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Splash />
    </>
  );
};

// SplashPage.mainLayout = BaseLayout;
// SplashPage.childLayout = SubLayout;
export default SplashPage;
